/*
 * Copyright (c) 2014 logpie.com
 * All rights reserved.
*/
package com.logpie.rocket.data;

public class MetricRecord {

	/**
	 * This is a class corresponding to the metric record in DB
	 *  {
  "requestID":"1DEASEWO-2232GDA2",  // The Random Number Generated by Clients
  "company":"logpie.com", 
  "platform":"java",  // Programming language Which Clients Use
  "application":"logpie",
  "software_version":"1.01",  // The Clients Version
  "environment":"alpha",
  "metrics":[
     {
        "component":"loginpage",
        "action":"register",
        "timestamp":9800284756345,
        "time":91
     },
     {
        "component":"loginpage",
        "action":"login",
        "timestamp":9800284756389,
        "time":27
     }
  ],
  "mobile_device":"true",
  "OS_type":"android",
  "OS_version":"4.1",
  "device_manufacture":"Samsung"
  "device_version":"Galaxy S3"
 }
	 */

	public static final String key_RequestID = "requestID";
	public static final String key_Company = "company";
	public static final String key_Platform = "platform";
	public static final String key_Application = "application";
	public static final String key_SoftwareVersion = "software_version";
	public static final String key_Component = "component";
	public static final String key_Metrics = "metrics";
	public static final String key_Action = "action";
	public static final String key_MetricTimeStamp = "timestamp";
	public static final String key_MetricTime = "time";
	public static final String key_MobileDevice = "mobile_device";
	public static final String key_OSType = "OS_type";
	public static final String key_OSVersion = "OS_version";
	public static final String key_DeviceManufacture = "device_manufacture";
	public static final String key_DeviceVersion = "device_version";
	public static final String key_Environment = "environment";
	
	//The fields below are mandatory
	private String mRequestID;
	private String mCompany;
	private String mPlatform;
	private String mApplication;
	private String mSoftwareVersion;
	private String mComponent;
    private String mAction;
    private String mMetricTime;
    private String mMetricTimeStamp;
    private String mEnvironment;
    private Boolean mIsMobileDevice;
    
	//The files below are optional
    private String mOSType;
    private String mOSVersion;
    private String mDeviceManufacture;
    private String mDeviceVersion;
	public String getRequestID() {
		return mRequestID;
	}
	public void setRequestID(String requestID) {
		mRequestID = requestID;
	}
	public String getCompany() {
		return mCompany;
	}
	public void setCompany(String company) {
		mCompany = company;
	}
	public String getPlatform() {
		return mPlatform;
	}
	public void setPlatform(String platform) {
		mPlatform = platform;
	}
	public String getApplication() {
		return mApplication;
	}
	public void setApplication(String application) {
		mApplication = application;
	}
	public String getSoftwareVersion() {
		return mSoftwareVersion;
	}
	public void setSoftwareVersion(String softwareVersion) {
		mSoftwareVersion = softwareVersion;
	}
	public String getComponent() {
		return mComponent;
	}
	public void setComponent(String component) {
		mComponent = component;
	}
	public String getAction() {
		return mAction;
	}
	public void setAction(String action) {
		mAction = action;
	}
	public String getMetricTime() {
		return mMetricTime;
	}
	public void setMetricTime(String metricTime) {
		mMetricTime = metricTime;
	}
	
	public String getmMetricTimeStamp() {
		return mMetricTimeStamp;
	}
	public void setmMetricTimeStamp(String mMetricTimeStamp) {
		this.mMetricTimeStamp = mMetricTimeStamp;
	}
	public static String getKeyMetrictimestamp() {
		return key_MetricTimeStamp;
	}
	public Boolean getIsMobileDevice() {
		return mIsMobileDevice;
	}
	public void setIsMobileDevice(Boolean isMobileDevice) {
		mIsMobileDevice = isMobileDevice;
	}
	public String getOSType() {
		return mOSType;
	}
	public void setOSType(String oSType) {
		mOSType = oSType;
	}
	public String getOSVersion() {
		return mOSVersion;
	}
	public void setOSVersion(String oSVersion) {
		mOSVersion = oSVersion;
	}
	public String getDeviceManufacture() {
		return mDeviceManufacture;
	}
	public void setDeviceManufacture(String deviceManufacture) {
		mDeviceManufacture = deviceManufacture;
	}
	public String getDeviceVersion() {
		return mDeviceVersion;
	}
	public void setDeviceVersion(String deviceVersion) {
		mDeviceVersion = deviceVersion;
	}
    public String getEnvironment() {
		return mEnvironment;
	}
	public void setEnvironment(String environment) {
		mEnvironment = environment;
	}

}
